### ISSUE TITLE
Expose tags as an input

### ISSUE THREAD

**Issue by nitrocode** [bschaatsbergen/terraform-gce-atlantis#64] opened 2023-01-06 17:34 UTC
https://github.com/bschaatsbergen/terraform-gce-atlantis/blob/88f71057b47fd89d31da5a8c57c4bd8f08a2615d/main.tf#L20

Note that you get this input out of the box with #57 using `module.this.tags`.

**Comment by bschaatsbergen** [comment] 2023-01-06 20:32
Closed in #71

**Closed by bschaatsbergen** 2023-01-06 20:32 UTC

**Comment by nitrocode** [comment] 2023-01-07 07:42
Why not also use that unit for 

https://github.com/bschaatsbergen/terraform-gce-atlantis/blob/34cd4457365989535c2e6b93049a45090c557642/main.tf#L277

https://github.com/bschaatsbergen/terraform-gce-atlantis/blob/34cd4457365989535c2e6b93049a45090c557642/main.tf#L293

Why do the tags need to be concatenated with `atlantis` as a tag? Couldn't you use that as the default value for `tags` input so it can be overwritten if desired?

**Comment by bschaatsbergen** [comment] 2023-01-07 09:53
@nitrocode, we create firewall rules and routes that are required e.g. a route to the public internet and a firewall rule to allow inbound health checks.

To not create these 'project-wide' we use tags to scope them to a particular instance.

Therefor we enforce the 'atlantis' tag, just to be sure that no unintended behaviour pops up.

**Comment by nitrocode** [comment] 2023-01-07 14:31
Interesting. Is there no other way to get the firewall rules to apply to this instance without a unique tag?

The static tagging seems too rigid to me. What if another instance was tagged with `atlantis`? What if multiple Atlantis servers were being run in the same account?

Could you expose a new input then such as `tags_firewall` or do you find it unlikely that someone would want to change the default atlantis tag?

**Comment by bschaatsbergen** [comment] 2023-01-07 16:29
I think that your point is very valid and I'll raise a new issue. Exposing a new var could solve the problem, optionally we could also replace the 'static' `atlantis` tag with a `atlantis` + random string to ensure that the route and firewall rule we create only belong to the instance, and a user can then decide to extra tags to just the instance or not. Thoughts?
